### ISSUE TITLE
CLang20 and layout_mode::INLINE.

### ISSUE THREAD

**Issue by jackbergus** [simdjson/simdjson#2738]
The inclusion of the "json_structure_analyzer.h" fails to compile in Clang20 on v4.6.4, as it raises the following issues:

```
simdjson/include/simdjson/internal/json_structure_analyzer.h:23:9: error: expected identifier before ‘,’ token
   23 |   INLINE,              // Single line: [1, 2, 3] or {"a": 1}

simdjson/include/simdjson/dom/fractured_json-inl.h:75:51: error: expected unqualified-id before ‘;’ token
   75 |   metrics.recommended_layout = layout_mode::INLINE;

simdjson/include/simdjson/dom/fractured_json-inl.h:536:29: error: expected unqualified-id before ‘:’ token
  536 |     case layout_mode::INLINE: 
```

The simple change of the ```layout_mode``` enum class as follows solves the compile issue, which mainly seems related to the uppercase INLINE keyword:

```
enum class layout_mode {
  INLINED,              // Single line: [1, 2, 3] or {"a": 1}
  COMPACT_MULTILINE,   // Multiple items per line with breaks
  TABLE,               // Tabular format for arrays of similar objects
  EXPANDED             // Traditional multi-line with indentation
};
```

Please consider that other compilers, such as g++, are not affected by the issue above.

**Comment by jackbergus** [comment]
p.s. The proposed changes are the following: https://github.com/simdjson/simdjson/commit/4dd9739e8617806e7fafa6211f9afe2487bc8d6a

**Comment by lemire** [comment]
I cannot produce: 

<img width="1048" height="83" alt="Image" src="https://github.com/user-attachments/assets/ceef4292-1407-4b34-b14a-d35c6a38f08d" />

**Comment by lemire** [comment]
What happens if you put...

```
#undef INLINE  
```

right before `#include "simdjson.h"` in your code ?

**Comment by jackbergus** [comment]
Yes, that was it, thanks.
